# Generated by Django 5.1.4 on 2025-01-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
