# Generated by Django 5.1.4 on 2025-01-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='study',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='to_study',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='to_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='work',
            field=models.BooleanField(default=False),
        ),
    ]
