# Generated by Django 5.1.4 on 2025-01-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_country_study_country_to_study_country_to_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='study',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='to_study',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='work',
            field=models.BooleanField(default=False),
        ),
    ]
