# Generated by Django 5.1.4 on 2025-01-28 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_city_study_city_to_study_city_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='city',
        ),
        migrations.RemoveField(
            model_name='country',
            name='embassy',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='embassy',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.country'),
            preserve_default=False,
        ),
    ]
