# Generated by Django 5.1.4 on 2025-01-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_country_city_remove_country_embassy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='study',
        ),
        migrations.RemoveField(
            model_name='user',
            name='to_work',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tu_study',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work',
        ),
    ]
