# Generated by Django 5.1.4 on 2025-01-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_homeproblem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.CharField(max_length=250),
        ),
    ]
