# Generated by Django 5.1.4 on 2025-02-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_latitude_remove_user_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='work',
            old_name='name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='work',
            name='dokument',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='experience',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='fon_number',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='location',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
