# Generated by Django 5.1.4 on 2025-02-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_workcategory_rename_name_work_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='experience',
            new_name='company_fon_number',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='fon_number',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='location',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='max_salary',
            new_name='work_stafka',
        ),
        migrations.RemoveField(
            model_name='work',
            name='min_salary',
        ),
        migrations.RemoveField(
            model_name='work',
            name='requirements',
        ),
    ]
