# Generated by Django 5.1.4 on 2025-02-08 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_experience_work_company_fon_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='city',
        ),
        migrations.RemoveField(
            model_name='work',
            name='country',
        ),
    ]
